### ISSUE TITLE
Cloudflare优选IP - Busyo's Blog

### ISSUE THREAD

**Issue by busyoGG** [busyoGG/busyoGG.github.io#37]
https://busyo.buzz/article/8583c53078ec/ 

 利用优选IP加快Cloudflare的访问速度，防止因为IP被墙导致的无法访问或者访问缓慢 - Busyo - Busyo's Blog

**Comment by KKKKKKD32** [comment]
报错
Traceback (most recent call last):
  File "C:\Users\K\Desktop\cloudf\11.py", line 81, in <module>
    url = url.replace('{RECORD_ID}', DNS_ID)
                                     ^^^^^^
NameError: name 'DNS_ID' is not defined

**Comment by busyoGG** [comment]
> @KKKKKKD32
> 报错
> Traceback (most recent call last):
>   File "C:\Users\K\Desktop\cloudf\11.py", line 81, in <module>
>     url = url.replace('{RECORD_ID}', DNS_ID)
>                                      ^^^^^^
> NameError: name 'DNS_ID' is not defined

我自己是正常的，可能是因为DNS_ID没有获取到值

**Comment by KKKKKKD32** [comment]
有什么办法解决吗

**Comment by busyoGG** [comment]
> @KKKKKKD32
> 有什么办法解决吗
> 

我是没啥办法，只能靠自己慢慢排查了，有问题问问AI（

**Comment by KKKKKKD32** [comment]
问题的根本原因是，获取DNS记录的过程没有正确找到并设置DNS_ID。我们需要确保所有步骤都正确执行，特别是在获取DNS记录ID时确保能够成功获取并赋值。请确保以下步骤和代码逻辑的正确性：

正确获取新IP地址。
从Cloudflare获取DNS记录列表，并确保能够找到所需的A记录。
使用找到的DNS记录ID更新该记录的IP地址。
下面是重新整理后的代码：
import requests
import json

# Cloudflare API 密钥
API_KEY = '1b482b79f2a487749ea169eefe0c07ed75a11'
# Cloudflare 账户邮箱
EMAIL = '3573908988@qq.com'
# 域名
DOMAIN = 'kkkdebk.xyz'
# A 记录名称
RECORD_NAME = '@'
# Cloudflare Zone ID
ZONE_ID = '2eb0addc3b875cd4cd55ab96ba6ea23c'

# Cloudflare API 请求头
headers = {
    'X-Auth-Email': EMAIL,
    'X-Auth-Key': API_KEY,
    'Content-Type': 'application/json'
}

# 获取最低延迟的 IP 地址
response = requests.get('https://monitor.gacjie.cn/api/client/get_ip_address')
if response.status_code == 200:
    data = response.json()
    if data['status']:
        # 从返回的数据中选择 delay 最小的 IP 地址
        min_delay_ip = min(data['info']['CM'] + data['info']['CU'] + data['info']['CT'], key=lambda x: x['delay'])
        NEW_IP = min_delay_ip['ip']
        print('API 请求成功 新 IP:', NEW_IP)
    else:
        print('API 请求失败：', data['msg'])
        exit()
else:
    print('获取 IP 地址失败：', response.status_code)
    exit()

# 获取 DNS 记录 ID
url = f'https://api.cloudflare.com/client/v4/zones/{ZONE_ID}/dns_records?type=A&name={RECORD_NAME}'
response = requests.get(url, headers=headers)
resJson = response.json()

if resJson['success']:
    data = resJson['result']
    DNS_ID = None
    for record in data:
        print("检查记录:", record)  # 输出调试信息
        if record['name'] == RECORD_NAME and record['type'] == 'A':
            DNS_ID = record['id']
            print("A 记录名称为", RECORD_NAME, "的 ID 为：", DNS_ID)
            break
    if not DNS_ID:
        print('未找到匹配的 DNS 记录')
        exit()
else:
    print('获取 DNS 记录失败：', resJson['errors'])
    exit()

# 设置 DNS 记录
data = {
    'type': 'A',
    'name': RECORD_NAME,
    'content': NEW_IP,
    'proxied': True
}

url = f'https://api.cloudflare.com/client/v4/zones/{ZONE_ID}/dns_records/{DNS_ID}'
response = requests.put(url, json=data, headers=headers)

# 处理 API 响应
if response.status_code == 200:
    print('A 记录 IP 修改成功！')
else:
    print(f'错误：{response.status_code} - {response.text}')

**Comment by KKKKKKD32** [comment]
你看一下他说的对不对

**Comment by KKKKKKD32** [comment]
if resJson['success']:
    data = resJson['result']
    DNS_ID = None
    for record in data:
        print("检查记录:", record)  # 输出调试信息
        if record['name'] == RECORD_NAME and record['type'] == 'A':
            DNS_ID = record['id']
            print("A 记录名称为", RECORD_NAME, "的 ID 为：", DNS_ID)
好像是这地方的问题，DNS_ID的值被设置为没有了

**Comment by busyoGG** [comment]
> @KKKKKKD32
> if resJson['success']:
>     data = resJson['result']
>     DNS_ID = None
>     for record in data:
>         print("检查记录:", record)  # 输出调试信息
>         if record['name'] == RECORD_NAME and record['type'] == 'A':
>             DNS_ID = record['id']
>             print("A 记录名称为", RECORD_NAME, "的 ID 为：", DNS_ID)
> 好像是这地方的问题，DNS_ID的值被设置为没有了

主要问题就是为什么DNS_ID的值不存在，我自己运行是正常获取的，你可能要排查这个问题

**Comment by 4jigo** [comment]
NameError                                 Traceback (most recent call last)
<ipython-input-6-5bc6b0a01d83> in <cell line: 81>()
     79 url = 'https://api.cloudflare.com/client/v4/zones/{ZONE_ID}/dns_records/{RECORD_ID}'
     80 url = url.replace('{ZONE_ID}', ZONE_ID)
---> 81 url = url.replace('{RECORD_ID}', DNS_ID)
     82 # 发送 API 请求
     83 response = requests.request("PUT",url, json=data, headers=headers)

NameError: name 'DNS_ID' is not defined
